// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.Data;

#nullable disable

namespace backend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112184020_update_payment_order_snapshot")]
    partial class update_payment_order_snapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Domain.Models.BookingCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("BookingCustomers");
                });

            modelBuilder.Entity("backend.Domain.Models.CODPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("boolean");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("CODPayments");
                });

            modelBuilder.Entity("backend.Domain.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Description = "Tôm hùm tươi nướng với bơ tỏi thơm lừng.",
                            Image = "",
                            IsActive = true,
                            Name = "Tôm Hùm Nướng Bơ Tỏi",
                            Price = 1200000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "Sò huyết xào me chua ngọt hấp dẫn.",
                            Image = "",
                            IsActive = true,
                            Name = "Sò Huyết Xào Me",
                            Price = 250000f,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Description = "Món ăn vặt quen thuộc với đủ topping.",
                            Image = "",
                            IsActive = true,
                            Name = "Bánh Tráng Trộn",
                            Price = 30000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Description = "Nước giải khát mát lạnh.",
                            Image = "",
                            IsActive = true,
                            Name = "Trà Tắc",
                            Price = 15000f,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Description = "Cafe truyền thống Việt Nam.",
                            Image = "",
                            IsActive = true,
                            Name = "Cafe Sữa Đá",
                            Price = 25000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            Description = "Bánh ngọt ăn kèm cafe.",
                            Image = "",
                            IsActive = true,
                            Name = "Bánh Ngọt",
                            Price = 35000f,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 7,
                            Category = 0,
                            Description = "Lẩu cá kèo dân dã miền Tây.",
                            Image = "",
                            IsActive = true,
                            Name = "Lẩu Cá Kèo",
                            Price = 300000f,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Description = "Bia tươi mát lạnh.",
                            Image = "",
                            IsActive = true,
                            Name = "Bia Hơi",
                            Price = 20000f,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 9,
                            Category = 0,
                            Description = "Món chay thanh đạm, bổ dưỡng.",
                            Image = "",
                            IsActive = true,
                            Name = "Đậu Hũ Kho Nấm",
                            Price = 80000f,
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Description = "Giúp giải nhiệt, tốt cho sức khỏe.",
                            Image = "",
                            IsActive = true,
                            Name = "Nước Ép Rau Má",
                            Price = 25000f,
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Description = "Cocktail thanh mát, dễ uống.",
                            Image = "",
                            IsActive = true,
                            Name = "Cocktail Mojito",
                            Price = 120000f,
                            RestaurantId = 6
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            Description = "Snack ăn kèm khi uống rượu.",
                            Image = "",
                            IsActive = true,
                            Name = "Snack Mix",
                            Price = 60000f,
                            RestaurantId = 6
                        });
                });

            modelBuilder.Entity("backend.Domain.Models.DishPromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AppliedPrice")
                        .HasColumnType("real");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<float?>("OriginalPrice")
                        .HasColumnType("real");

                    b.Property<int>("PromotionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("PromotionId");

                    b.ToTable("DishPromotions");
                });

            modelBuilder.Entity("backend.Domain.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("backend.Domain.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("backend.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliedPromotionId")
                        .HasColumnType("integer");

                    b.Property<string>("AppliedVoucherCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("backend.Domain.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("backend.Domain.Models.OrderPromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<float>("MinOrderValue")
                        .HasColumnType("real");

                    b.Property<int>("PromotionId")
                        .HasColumnType("integer");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("OrderPromotions");
                });

            modelBuilder.Entity("backend.Domain.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("backend.Domain.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("OrderSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("backend.Domain.Models.PaymentTransactionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentTransactionLogs");
                });

            modelBuilder.Entity("backend.Domain.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer");

                    b.Property<float>("DiscountValue")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoucherCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Khuyến mãi 20% cho tất cả món hải sản trong menu.",
                            DiscountType = 0,
                            DiscountValue = 20f,
                            EndDate = new DateTime(2025, 12, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7846),
                            RestaurantId = 1,
                            StartDate = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7845),
                            TargetType = 2,
                            Title = "Giảm 20% Hải Sản"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giảm 15k cho đơn hàng từ 50k trở lên.",
                            DiscountType = 1,
                            DiscountValue = 15000f,
                            EndDate = new DateTime(2026, 1, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7856),
                            RestaurantId = 2,
                            StartDate = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7855),
                            TargetType = 1,
                            Title = "Combo Sinh Viên"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Áp dụng cho tất cả đồ uống trong menu.",
                            DiscountType = 0,
                            DiscountValue = 33.3f,
                            EndDate = new DateTime(2025, 12, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7859),
                            RestaurantId = 3,
                            StartDate = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7858),
                            TargetType = 0,
                            Title = "Mua 2 Tặng 1"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Giảm 10% cho tất cả món chay vào ngày Rằm.",
                            DiscountType = 0,
                            DiscountValue = 10f,
                            EndDate = new DateTime(2026, 2, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7861),
                            RestaurantId = 5,
                            StartDate = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7861),
                            TargetType = 2,
                            Title = "Khuyến Mãi Ăn Chay"
                        });
                });

            modelBuilder.Entity("backend.Domain.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("backend.Domain.Models.RecipeReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("RecipeReviews");
                });

            modelBuilder.Entity("backend.Domain.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("backend.Domain.Models.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("backend.Domain.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdultCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChildCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ReservationTime")
                        .HasColumnType("interval");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("backend.Domain.Models.ReservationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationStatusHistories");
                });

            modelBuilder.Entity("backend.Domain.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("CloseTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePublicId")
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpenTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường Biển, TP. HCM",
                            AverageRating = 0.0,
                            Category = 1,
                            CloseTime = "22:00",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7751),
                            Description = "Chuyên các món hải sản tươi sống, không gian sang trọng.",
                            IsHidden = false,
                            Latitude = 10.776899999999999,
                            Longitude = 106.7009,
                            Name = "Nhà Hàng Hải Sản Biển Xanh",
                            OpenTime = "09:00",
                            OwnerId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Đường Lê Lợi, Hà Nội",
                            AverageRating = 0.0,
                            Category = 2,
                            CloseTime = "23:00",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7754),
                            Description = "Quán ăn vặt bình dân, giá rẻ, hợp túi tiền sinh viên.",
                            IsHidden = false,
                            Latitude = 21.028500000000001,
                            Longitude = 105.85420000000001,
                            Name = "Quán Ăn Vỉa Hè",
                            OpenTime = "15:00",
                            OwnerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Đường Nguyễn Huệ, Đà Nẵng",
                            AverageRating = 0.0,
                            Category = 4,
                            CloseTime = "21:00",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7757),
                            Description = "Quán cafe view đẹp, thích hợp để học tập và làm việc.",
                            IsHidden = false,
                            Latitude = 16.054400000000001,
                            Longitude = 108.2022,
                            Name = "Cafe Góc Phố",
                            OpenTime = "07:00",
                            OwnerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "654 Đường Hòa Bình, Cần Thơ",
                            AverageRating = 0.0,
                            Category = 7,
                            CloseTime = "00:00",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7759),
                            Description = "Chuyên các món nhậu dân dã, không gian thoải mái.",
                            IsHidden = false,
                            Latitude = 10.045199999999999,
                            Longitude = 105.7469,
                            Name = "Quán Nhậu Bình Dân",
                            OpenTime = "16:00",
                            OwnerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Address = "321 Đường Nguyễn Văn Linh, Huế",
                            AverageRating = 0.0,
                            Category = 3,
                            CloseTime = "21:00",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7761),
                            Description = "Nhà hàng chay thanh tịnh, chuyên phục vụ các món ăn tốt cho sức khỏe.",
                            IsHidden = false,
                            Latitude = 16.463699999999999,
                            Longitude = 107.5909,
                            Name = "Nhà Hàng Chay Tâm An",
                            OpenTime = "08:00",
                            OwnerId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "888 Đường Trần Hưng Đạo, Hà Nội",
                            AverageRating = 0.0,
                            Category = 6,
                            CloseTime = "03:00",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7763),
                            Description = "Bar sôi động với DJ và nhạc EDM cực chất.",
                            IsHidden = false,
                            Latitude = 21.033799999999999,
                            Longitude = 105.84999999999999,
                            Name = "Bar The Night",
                            OpenTime = "20:00",
                            OwnerId = 6,
                            Status = 0
                        });
                });

            modelBuilder.Entity("backend.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Hải sản rất tươi, nhân viên phục vụ nhiệt tình.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7890),
                            Rating = 5,
                            RestaurantId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Không gian đẹp, giá hơi cao nhưng xứng đáng.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7892),
                            Rating = 4,
                            RestaurantId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Quán ăn vặt ngon, hợp túi tiền.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7893),
                            Rating = 4,
                            RestaurantId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Đông khách, phục vụ hơi chậm.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7894),
                            Rating = 3,
                            RestaurantId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Cafe ngon, view đẹp, yên tĩnh học bài.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7896),
                            Rating = 5,
                            RestaurantId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Không gian ổn, giá hơi cao.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7897),
                            Rating = 4,
                            RestaurantId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Đồ nhậu ngon, giá rẻ.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7898),
                            Rating = 4,
                            RestaurantId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Không gian thoải mái, thích hợp tụ tập bạn bè.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7900),
                            Rating = 5,
                            RestaurantId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Đồ ăn chay ngon, cảm giác nhẹ nhàng.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7901),
                            Rating = 5,
                            RestaurantId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Món ăn đa dạng, nhân viên thân thiện.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7902),
                            Rating = 4,
                            RestaurantId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Bar sôi động nhưng hơi ồn.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7904),
                            Rating = 3,
                            RestaurantId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Nhạc DJ cực chất, không gian sôi động.",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7905),
                            Rating = 5,
                            RestaurantId = 6,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("backend.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BusinessOwnerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("BusinessOwnerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Admin Street",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7509),
                            Email = "l3acasha@gmail.com",
                            IsActive = true,
                            Phone = "0386001106",
                            Role = 0,
                            UserName = "admin",
                            UserPassword = "$2a$11$S3CqbavZCGuTIVa7/gxhq.uhpOZzGZtyAv0xSnXnUJ6pNzENH0T86"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "456 Business Street",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7512),
                            Email = "nhocsieuquay131023@gmail.com",
                            IsActive = true,
                            Phone = "0827749293",
                            Role = 1,
                            UserName = "business",
                            UserPassword = "$2a$11$S3CqbavZCGuTIVa7/gxhq.uhpOZzGZtyAv0xSnXnUJ6pNzENH0T86"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "789 User Street",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7515),
                            Email = "phatqq0@gmail.com",
                            IsActive = true,
                            Phone = "0395042018",
                            Role = 2,
                            UserName = "user",
                            UserPassword = "$2a$11$S3CqbavZCGuTIVa7/gxhq.uhpOZzGZtyAv0xSnXnUJ6pNzENH0T86"
                        },
                        new
                        {
                            UserId = 4,
                            Address = "987 Business Street",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7517),
                            Email = "test1@gmail.com",
                            IsActive = true,
                            Phone = "0829949293",
                            Role = 1,
                            UserName = "business",
                            UserPassword = "$2a$11$S3CqbavZCGuTIVa7/gxhq.uhpOZzGZtyAv0xSnXnUJ6pNzENH0T86"
                        },
                        new
                        {
                            UserId = 5,
                            Address = "654 User Street",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7519),
                            Email = "test2@gmail.com",
                            IsActive = true,
                            Phone = "0395992018",
                            Role = 2,
                            UserName = "user",
                            UserPassword = "$2a$11$S3CqbavZCGuTIVa7/gxhq.uhpOZzGZtyAv0xSnXnUJ6pNzENH0T86"
                        },
                        new
                        {
                            UserId = 6,
                            Address = "321 Business Street",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7521),
                            Email = "test3@gmail.com",
                            IsActive = true,
                            Phone = "0826649293",
                            Role = 1,
                            UserName = "business",
                            UserPassword = "$2a$11$S3CqbavZCGuTIVa7/gxhq.uhpOZzGZtyAv0xSnXnUJ6pNzENH0T86"
                        },
                        new
                        {
                            UserId = 7,
                            Address = "136 User Street",
                            CreatedAt = new DateTime(2025, 11, 12, 18, 40, 19, 725, DateTimeKind.Utc).AddTicks(7574),
                            Email = "test4@gmail.com",
                            IsActive = true,
                            Phone = "0395042018",
                            Role = 2,
                            UserName = "user",
                            UserPassword = "$2a$11$S3CqbavZCGuTIVa7/gxhq.uhpOZzGZtyAv0xSnXnUJ6pNzENH0T86"
                        });
                });

            modelBuilder.Entity("backend.Domain.Models.VNPayPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankCode")
                        .HasColumnType("text");

                    b.Property<string>("CardType")
                        .HasColumnType("text");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("text");

                    b.Property<string>("VnpTxnRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("VNPayPayments");
                });

            modelBuilder.Entity("backend.Domain.Models.ZaloPayPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppTransId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<string>("ZpTransId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("ZaloPayPayments");
                });

            modelBuilder.Entity("backend.Domain.Models.BookingCustomer", b =>
                {
                    b.HasOne("backend.Domain.Models.Reservation", "Reservation")
                        .WithMany("Customers")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("backend.Domain.Models.CODPayment", b =>
                {
                    b.HasOne("backend.Domain.Models.Payment", "Payment")
                        .WithOne("CODPayment")
                        .HasForeignKey("backend.Domain.Models.CODPayment", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("backend.Domain.Models.Dish", b =>
                {
                    b.HasOne("backend.Domain.Models.Restaurant", "Restaurant")
                        .WithMany("Dishes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("backend.Domain.Models.DishPromotion", b =>
                {
                    b.HasOne("backend.Domain.Models.Dish", "Dish")
                        .WithMany("DishPromotions")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Models.Promotion", "Promotion")
                        .WithMany("DishPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("backend.Domain.Models.Favorite", b =>
                {
                    b.HasOne("backend.Domain.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Models.Notification", b =>
                {
                    b.HasOne("backend.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Models.Order", b =>
                {
                    b.HasOne("backend.Domain.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Models.OrderItem", b =>
                {
                    b.HasOne("backend.Domain.Models.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("backend.Domain.Models.OrderPromotion", b =>
                {
                    b.HasOne("backend.Domain.Models.Promotion", "Promotion")
                        .WithMany("OrderPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId");

                    b.Navigation("Promotion");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("backend.Domain.Models.PasswordResetToken", b =>
                {
                    b.HasOne("backend.Domain.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Models.Payment", b =>
                {
                    b.HasOne("backend.Domain.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("backend.Domain.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("backend.Domain.Models.PaymentTransactionLog", b =>
                {
                    b.HasOne("backend.Domain.Models.Payment", "Payment")
                        .WithMany("TransactionLogs")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("backend.Domain.Models.Promotion", b =>
                {
                    b.HasOne("backend.Domain.Models.Restaurant", "Restaurant")
                        .WithMany("Promotions")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("backend.Domain.Models.Recipe", b =>
                {
                    b.HasOne("backend.Domain.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Models.RecipeReview", b =>
                {
                    b.HasOne("backend.Domain.Models.Recipe", "Recipe")
                        .WithMany("RecipeReviews")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Models.User", "User")
                        .WithMany("RecipeReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Models.Refund", b =>
                {
                    b.HasOne("backend.Domain.Models.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("backend.Domain.Models.Reservation", b =>
                {
                    b.HasOne("backend.Domain.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Models.ReservationStatusHistory", b =>
                {
                    b.HasOne("backend.Domain.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("backend.Domain.Models.Restaurant", b =>
                {
                    b.HasOne("backend.Domain.Models.User", "Owner")
                        .WithMany("Restaurants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("backend.Domain.Models.Review", b =>
                {
                    b.HasOne("backend.Domain.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Models.User", b =>
                {
                    b.HasOne("backend.Domain.Models.User", "BusinessOwner")
                        .WithMany("Staffs")
                        .HasForeignKey("BusinessOwnerId");

                    b.Navigation("BusinessOwner");
                });

            modelBuilder.Entity("backend.Domain.Models.VNPayPayment", b =>
                {
                    b.HasOne("backend.Domain.Models.Payment", "Payment")
                        .WithOne("VNPayPayment")
                        .HasForeignKey("backend.Domain.Models.VNPayPayment", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("backend.Domain.Models.ZaloPayPayment", b =>
                {
                    b.HasOne("backend.Domain.Models.Payment", "Payment")
                        .WithOne("ZaloPayPayment")
                        .HasForeignKey("backend.Domain.Models.ZaloPayPayment", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("backend.Domain.Models.Dish", b =>
                {
                    b.Navigation("DishPromotions");
                });

            modelBuilder.Entity("backend.Domain.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("backend.Domain.Models.Payment", b =>
                {
                    b.Navigation("CODPayment");

                    b.Navigation("Refunds");

                    b.Navigation("TransactionLogs");

                    b.Navigation("VNPayPayment");

                    b.Navigation("ZaloPayPayment");
                });

            modelBuilder.Entity("backend.Domain.Models.Promotion", b =>
                {
                    b.Navigation("DishPromotions");

                    b.Navigation("OrderPromotions");
                });

            modelBuilder.Entity("backend.Domain.Models.Recipe", b =>
                {
                    b.Navigation("RecipeReviews");
                });

            modelBuilder.Entity("backend.Domain.Models.Reservation", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("backend.Domain.Models.Restaurant", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("backend.Domain.Models.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RecipeReviews");

                    b.Navigation("Recipes");

                    b.Navigation("Restaurants");

                    b.Navigation("Reviews");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
